module.exports = {
  STEPS: {
    LAPTOP_ADD: 'laptop_add',
    LAPTOP_RETURN: 'laptop_return',
    STUDENT_ADD_NAME: 'student_add_name',
    STUDENT_ADD_DURATION: 'student_add_duration',
    TEACHER_ADD: 'teacher_add',
    TEACHER_ISSUE_NAME: 'teacher_issue_name',
    TEACHER_RETURN_NAME: 'teacher_return_name',
    SUPPORT_ADD: 'support_add',
    SUPPORT_REMOVE: 'support_remove',
    ISSUE_STUDENT_SELECT: 'issue_student_select',
    ISSUE_LAPTOP_SELECT: 'issue_laptop_select',
    STUDENT_STATUS_SELECT: 'student_status_select',
    STUDENT_EXTEND_DAYS: 'student_extend_days',
    TEACHER_ISSUE_LAPTOPS: 'teacher_issue_laptops',
    TEACHER_RETURN_PICK: 'teacher_return_pick',
  },
  MENU: {
    LAPTOPS: '💻 Ноутбуки',
    TEACHERS: '👨‍🏫 Учителя',
    STUDENTS: '👨‍🎓 Ученики',
    OCCUPIED: '⏳ Занятые',
    SUPPORTS: '👥 Супорты',
    BACK: '◀️ Назад',
    CANCEL: '❌ Отмена',
    ADD_LAPTOP: '➕ Добавить ноут',
    LAPTOP_OCCUPIED: '📋 Занятые ноуты',
    ISSUE_LAPTOP: '📤 Выдать ноут',
    RETURN_LAPTOP: '📥 Вернуть ноут',
    ADD_TEACHER: '➕ Добавить учителя',
    TEACHER_ISSUE: '📤 Выдать ноутбуки',
    TEACHER_RETURN: '📥 Возврат',
    RETURN_ALL: '📥 Вернуть все',
    RETURN_PICK: '📥 Выбрать ноуты',
    ADD_STUDENT: '➕ Добавить ученика',
    STUDENT_LIST: '📋 Список учеников',
    STUDENT_STATUS: 'ℹ️ Статус ученика',
    ADD_SUPPORT: '➕ Добавить супорта',
    REMOVE_SUPPORT: '➖ Удалить супорта',
  },
};
