module.exports = {
  STEPS: {
    SUPPORT_ADD: 'support_add',
    SUPPORT_REMOVE: 'support_remove',
    MENTOR_ADD: 'mentor_add',
    MENTOR_REMOVE: 'mentor_remove',
    WAREHOUSE_SET_TOTAL: 'warehouse_set_total',
    TAKE_WAREHOUSE_QTY: 'take_warehouse_qty',
    TAKE_WAREHOUSE_DEST: 'take_warehouse_dest',
    TAKE_MENTOR_CLASS: 'take_mentor_class',
    TAKE_FROM_MENTOR_PICK: 'take_from_mentor_pick',
    TAKE_FROM_MENTOR_QTY_INPUT: 'take_from_mentor_qty_input',
    TAKE_FROM_MENTOR_DEST: 'take_from_mentor_dest',
    TAKE_FROM_COWORKING_QTY: 'take_from_coworking_qty',
    MENTOR_REQUEST_QTY: 'mentor_request_qty',
    MENTOR_REQUEST_CABINET: 'mentor_request_cabinet',
    MENTOR_RETURN_QTY: 'mentor_return_qty',
    MENTOR_RETURN_QTY_INPUT: 'mentor_return_qty_input',
    MENTOR_RETURN_SUPPORT: 'mentor_return_support',
  },
  MENU: {
    WAREHOUSE: '📦 Склад',
    INFO: 'ℹ️ Информация',
    MENTORS: '👨‍🏫 Менторы',
    SUPPORTS: '👥 Супорты',
    BACK: '◀️ Назад',
    CANCEL: '❌ Отмена',
    TAKE_FROM_WAREHOUSE: '📤 Взять со склада',
    TAKE_FROM_MENTOR: '📥 Забрать у ментора',
    TAKE_FROM_COWORKING: '📥 Забрать с коворкинга',
    WAREHOUSE_SET: '⚙️ Размер склада',
    ADD_SUPPORT: '➕ Добавить супорта',
    REMOVE_SUPPORT: '➖ Удалить супорта',
    ADD_MENTOR: '➕ Добавить ментора',
    REMOVE_MENTOR: '➖ Удалить ментора',
    MENTOR_REQUEST: '📦 Запросить ноутбуки',
    MENTOR_RETURN: '📥 Вернуть ноутбуки',
    RETURN_ALL: '📥 Все',
    RETURN_PICK: '📥 Несколько',
    DEST_COWORKING: '🏢 Коворкинг',
    DEST_MENTOR: '👨‍🏫 Ментору',
    TO_WAREHOUSE: '📦 На склад',
    TO_COWORKING: '🏢 На коворкинг',
    TAKE_ALL: '📥 Забрать всё',
    TAKE_CUSTOM: '🔢 Забрать N шт',
  },
};
